### ISSUE TITLE
Alfred 3 에서 실행 에러

### ISSUE THREAD

**Issue by choru-k** [Kuniz/alfnaversearch#10]
0.0.12 버전까지는 Alfred 3 에서 실행이 되었는데 새로운 0.0.13 버전에서는 alfred 3 에서 실행할 경우
Please update to the latest version of Alfred 라는 에러가 뜨네요.
<img width="1212" alt="Screen Shot 2019-12-22 at 15 22 58" src="https://user-images.githubusercontent.com/8134523/71318074-f033a200-24ce-11ea-8b83-95855dac14fa.png">

**Comment by moon1ite** [comment]
@g6ling 

일단 불편하시면 v0.0.12를 다운받아 설치를 하시고 `endic_naver_search.py` 를 수정하시면 됩니다.

1. 다운받고 alfred에 설치 후 설치 경로로 이동
<img src="https://user-images.githubusercontent.com/24843996/71554369-7d43a180-2a61-11ea-835a-11e8985fb0ee.png" width=30%>

2. [`endic_naver_search.py`의 L25 수정](https://github.com/Kuniz/alfnaversearch/pull/6)
- 변경 전
```python
url = 'http://ac.endic.naver.com/ac'
```
- 변경 후
```python
url = 'https://ac.dict.naver.com/enendict/ac'
```

**Comment by choru-k** [comment]
👍 감사합니다. 잘 해결 되었습니다.
