### ISSUE TITLE
스페인어 사전 오류

### ISSUE THREAD

**Issue by davidkunin** [Kuniz/alfnaversearch#11]
안녕하세요 워크플로우를 너무 잘 쓰고 있습니다.
다름이 아니라, 이번에 스페인어 공부를 시작하면서 사전을 사용하려고 하는데, 아래와 같은 오류가 발생해서 문의 드립니다. 감사합니다. 

<img width="605" alt="스크린샷 2020-02-06 오후 10 29 52" src="https://user-images.githubusercontent.com/37537302/73980362-56b23980-4930-11ea-97ff-1024d5644eea.png">

**Comment by Kuniz** [comment]
v0.0.14에서 해결하였습니다. 제보 감사합니다!
