### ISSUE TITLE
Error with Naver Spanish Dictionary 

### ISSUE THREAD

**Issue by 441201V** [Kuniz/alfnaversearch#14]
<img width="766" alt="naver spanishdict error" src="https://user-images.githubusercontent.com/20138592/82122381-4c74c680-97ce-11ea-8e5f-0a23b9feb8bf.png">

안녕하세요. 만들어주신 워크플로우 정말 잘 사용하고 있습니다.
다만, 스페인어 사전 검색시 위와 같은 오류가 뜨는 것으로 보여 제보드립니다.
감사합니다!

**Comment by Kuniz** [comment]
v0.0.14에서 해결하였습니다. 제보 감사합니다!
