### ISSUE TITLE
독일어, 스페인어 사전 오류 문의

### ISSUE THREAD

**Issue by kimbohyu** [Kuniz/alfnaversearch#15]
안녕하세요?
사전 기능 덕분에 정말 잘 쓰고 있습니다.
몇일 전 부터 영어는 정상 기능 하는데 독일어랑 스페인어 사전이 작동되지 않아서 그런데
이전처럼 url이 변경되어서 그런 것일까요? 
search 파일 안에 url 경로를 어떻게 바꾸면 다시 정상적으로 작동할지 알려주실 수 있나요?
감사합니다.

**Comment by Kuniz** [comment]
[v0.0.15](https://github.com/Kuniz/alfnaversearch/releases/tag/v0.0.15) 에서 해결되었습니다!

새로 [다운로드](https://github.com/Kuniz/alfnaversearch/raw/master/Naver%20Search.alfredworkflow) 부탁드립니다 :) 

제보 감사합니다! 👍
