### ISSUE TITLE
국어사전이 동작하지 않습니다.

### ISSUE THREAD

**Issue by deepredk** [Kuniz/alfnaversearch#16]
<img width="598" alt="스크린샷 2021-01-06 오후 11 00 11" src="https://user-images.githubusercontent.com/33937365/103776616-02996300-5073-11eb-8952-61d551ecffec.png">

수개월째 Kuniz님의 워크플로우 잘 쓰고있습니다!
여태까지는 영한사전만 이용해왔는데, 요즘 국어사전을 많이 찾아서 nak를 이용했는데 오류가 나더라구요. 확인 부탁드립니다!

**Comment by Kuniz** [comment]
v0.0.16에서 해결했습니다 ~ 새로 다운로드 부탁드려요!

[`다운로드`](https://github.com/Kuniz/alfnaversearch/raw/master/Naver%20Search.alfredworkflow)

**Comment by deepredk** [comment]
감사합니다! ☺️
