### ISSUE TITLE
아이콘 변경 제안드려봅니다.

### ISSUE THREAD

**Issue by yellowphant** [Kuniz/alfnaversearch#19]
안녕하세요~
Kuniz님 덕분에 워크플로우 잘 활용하고 있습니다. 감사합니다.

업데이트 해주실 때마다 매번 아이콘을 변경해서 사용했는데요.
네이버 검색 아이콘과 사전 아이콘을 구분하면 사용하는데 편할 거 같아서 제안 드려봅니다.

감사합니다.

아이콘 첨부드립니다.
https://yellow.d.pr/cbaA0z

**Comment by Kuniz** [comment]
오! 좋습니다. 다음버전에 반영해두겠습니다 :)
