### ISSUE TITLE
중국어 사전 query 변경

### ISSUE THREAD

**Issue by ScottyKim** [Kuniz/alfnaversearch#2]
안녕하세요.
오늘 설치 해봤는데, 네이버 중국어 사전의 url이 변경 되어서
현재 nac 부분의 cndic.naver.com 에서 zh.dict.naver.com 으로 변경이 필요할 듯 합니다.

https://zh.dict.naver.com/#/search?range=all&query={query}

로 변경 해주시면 사용에 정말 도움이 많이 될 듯 합니다.

감사합니다.

**Comment by Kuniz** [comment]
새로 베타버전 중국어사전이 나왔나보군요.
확인해 보고 수정하겠습니다 ~
감사합니다.
