### ISSUE TITLE
[기능 건의] 사전 검색 결과 클립보드 복사 기능

### ISSUE THREAD

**Issue by hongji3354** [Kuniz/alfnaversearch#23]
사전 사용시 결과만 복사해서 사용하는 경우가 많은 것으로 알고 있는데 Command + Enter시 결과를 클립보드에 추가하는 것은 어떨까요?

**Comment by Kuniz** [comment]
https://github.com/Kuniz/alfnaversearch/releases/tag/v0.3.0 

v0.3.0 에 반영했습니다 ~ 확인부탁드려요.

**Comment by harryhan24** [comment]
클립보드 기능 사용시 결과가 입력되는게 아니라 nae {query}로 입력된 {query}만 클립보드에 복사되더라구요!
