### ISSUE TITLE
naver map 검색 API가 바뀌었나봐요?

### ISSUE THREAD

**Issue by inchanS** [Kuniz/alfnaversearch#24]
다른건 모두 잘 되는데 naver map 검색만 status 500 에러가 나타나네요. 

파이썬 파일에 있는 `https://map.naver.com/v5/api/search`
이 URL 확인해보니 뭔가 바뀐것 같아요 ;;

**Comment by Kuniz** [comment]
그렇네요. 확인해보겠습니다 ~

**Comment by inchanS** [comment]
https://github.com/inchanS/alfnaversearch/commit/43ef7be3dab62c56e4a489f3e0a1257a782b7581

그냥 이리저리 만져보다 일단 현재 잘 되기는 하는데, 
어디 내놓기 부끄러운 코드 수정이라 차마 PR은 못하고, 
혹시 수정하실때 참고가 될까해서 남겨봅니다. ;; 

**def get_data의 params key 중에서 coords 값이** 현재 서울 중심지로 해서 넣어놨지만, 
이걸 최종사용자의 ip주소 또는 알프레드의 권한으로 사용자 현재위치값을 넣는법?? 등으로 해야할 것 같은데 

파이썬이랑 alfred 워크플로우는 잘몰라서 전혀 감이 안잡히네요. ㅠ

**Comment by inchanS** [comment]
관련 문제 개선 코드 PR 드렸습니다. 
미흡하지만 한번 살펴봐주세요
