### ISSUE TITLE
영사전이 동작하지 않는 이슈

### ISSUE THREAD

**Issue by huneea** [Kuniz/alfnaversearch#28]
영어사전 검색이 이제 안되네요. 404 오류가 발생합니다.

<img width="715" alt="image" src="https://github.com/Kuniz/alfnaversearch/assets/67728580/305730cd-256d-47c8-b5ca-1305f9294e21">

**Comment by Kuniz** [comment]
안녕하세요, 혹시 현재 버전 몇을 사용하고 계신지 알 수 있을까요?
재연이 안되어서요.

확인 부탁드립니다.

**Comment by lnto3408** [comment]
저도 안되네요, Alfred 4.8 으로 업글했는데요 동일하네요.

**Comment by Kuniz** [comment]
그러면 구체적인 상황 파악을 위해서 혹시 아래 스크린샷에서 "버전"이 0.3.3인지 여부(아닐경우 업데이트 필요)와, 맞음에도 불구하고 안된다면 export해서 파일을 보내주실 수 있으실까요? 재연이 안되어서요.

![Screenshot 2024-05-16 at 9 30 24 PM](https://github.com/Kuniz/alfnaversearch/assets/2136167/84273d5b-c5d3-475b-8dbe-b337a2f057de)

**Comment by lnto3408** [comment]
이슈가 발생했던 버전은 0.2.1 으로 좀 오래된 버전이였군요. 
export 된 파일 첨부드립니다. 
[Naver Search.zip](https://github.com/Kuniz/alfnaversearch/files/15336256/Naver.Search.zip)

최신 버전(0.3.3)으로 업데이트 하니 잘 동작합니다. 
감사합니다.

**Comment by huneea** [comment]
@Kuniz 
아 저도 오래된 버전(0.1.3 버전) 사용중이었네요.
안되길래 최신버전을 받아서 실행해봤는데도 안되길래 문의글 남겼는데요.
이건 제 로컬에서 알프레드의 설정파일 저장위치를 icloud로 해놨더니 레거시 버전(0.1.3)이 삭제되지 않고 남아있는 이슈였습니다. (바로 반영되지 않은 이슈)
0.1.3 버전과 0.3.3 버전이 둘다 import 된 상태로 확인되었습니다.
알프레드 설정파일 저장위치를 로컬 저장소로 변경하고 해보니 최신버전에서는 정상 동작합니다.
확인 감사합니다!

**Comment by Kuniz** [comment]
@lnto3408
확인 감사합니다 ~

@jhh992000 
해결되었다니 다행이에요. iCloud에 설정파일을 넣으면 그런 이슈가 있을 수 있군요.
리포팅 감사해요!
