### ISSUE TITLE
오타 수정 부탁드려요

### ISSUE THREAD

**Issue by starpiens** [Kuniz/alfnaversearch#3]
안녕하세요!
일반 네이버 검색에서, (파싱된)다른 결과들은 Search Naver for ... 로 출력되는데
첫 번째 검색결과만 자꾸 Search Naver Endic for ... 이런 식으로 나오길래
확인해 봤더니 오타가 있네요! 수정 부탁드립니다
https://github.com/Kuniz/alfnaversearch/blob/ed3d7f9e640b3b3065dc29592eea0664e2a3dd92/workflow/naver_search.py#L53

**Comment by Kuniz** [comment]
그렇네요. PR, 감사합니다!!

**Comment by ghost** [comment]
`Naver Search.alfredworkflow` 파일에 반영이 안된 것 같습니다. 여전히 이 문제가 발생하네요.
