### ISSUE TITLE
간헐적인 HTTP Error 503: Service temporarily Unavailable 오류

### ISSUE THREAD

**Issue by ghost** [Kuniz/alfnaversearch#5]
<img width="679" alt="스크린샷 2019-06-25 오후 9 27 29" src="https://user-images.githubusercontent.com/32840866/60098293-20a0ba80-9790-11e9-87f3-0bcc47480b01.png">

안녕하세요. 유용한 워크플로우 감사합니다.
문제는 아니지만 가끔 단어를 (빠르게) 입력하다보면 위와 같은 오류가 뜰 때가 있어요.
감사합니다~

**Comment by unwmun-smobile** [comment]
저도 동일한 문제가 가끔 발생합니다. 
주로 단어 입력 후 마지막 단어를 입력하면 발생합니다. 존재하지 않는 단어를 검색할 때 발생되는 것 같네요.

NaverSearch Kit - v0.0.11
Alfred - 4.0.3 [1092]

**Comment by Kuniz** [comment]
적용하였습니다! 

https://github.com/Kuniz/alfnaversearch/releases/tag/v0.0.13
