### ISSUE TITLE
Naver endic(nae) 자동완성 불가

### ISSUE THREAD

**Issue by innocarpe** [Kuniz/alfnaversearch#7]
@Kuniz 님 안녕하세요, 저에게 있어 맥 사용 중 가장 빠르게 영단어 뜻을 찾을 수 있어 정말 오랫동안 잘 써왔습니다.

어제부턴가 `nae QUERY` 가 503 에러와 함께 동작하지 않네요. 잠깐 살펴보니 새 네이버 검색어 서비스를 만들고 있는 것 같더라구요. 

`https://en.dict.naver.com` 로 베이스 도메인이 일단 바뀐 것 같은데 `naj` 같이 

`https://ja.dict.naver.com/ac?st=111&r_lt=111&n_kojpdic=111&q=TEST` 같은 방식으로는 동작하지 않네요.. 😢 

혹시 해결 방법을 찾으신다면 수정해주시면 정말 감사하겠습니다!

**Comment by Kuniz** [comment]
PR 보내주신 부분 적용 했습니다!

https://github.com/Kuniz/alfnaversearch/releases/tag/v0.0.13
