### ISSUE TITLE
v0.0.12 릴리즈 파일 오류 (Endic 도메인 업데이트)

### ISSUE THREAD

**Issue by innocarpe** [Kuniz/alfnaversearch#8]
이번 Endic 도메인 변경하신 커밋이 v0.0.12 릴리즈에 포함되어 있는데 릴리즈 파일을 업데이트하지 않으셨나 싶어요. 다운받아 보니 Endic 도메인이 그대로여서 이슈 남겨봅니다!

**Comment by Kuniz** [comment]
넵! PR 적용 후, 릴리즈 했습니다. 감사합니다!

https://github.com/Kuniz/alfnaversearch/releases/tag/v0.0.13
